/**
 * Seed 20 job offers for company Google.
 * Usage: import and call from browser console while logged in as a company user,
 * or call from a temporary component.
 *
 *   import { seedJobs } from './scripts/seedJobs'
 *   seedJobs()
 */
import { collection, addDoc, serverTimestamp } from 'firebase/firestore'
import { db } from '../firebase/config'

const COMPANY_ID = 'S1IjGuWKDmRgATAeW6H8'

const jobs = [
  // ─── Junior (0-2 años) ────────────────────────────────────────────────────
  {
    title: 'Desarrollador Frontend Junior (React)',
    description: 'Buscamos un desarrollador frontend junior con conocimientos en React, HTML, CSS y JavaScript. Trabajarás en el equipo de interfaces de usuario construyendo componentes reutilizables y colaborando con diseñadores UX. Ideal para alguien que quiere crecer en un entorno de alto impacto.',
    work_modality: 'Remote',
    country: 'Colombia',
    min_salary: 2500000,
    max_salary: 4000000,
    years_experience_required: 1,
    max_applicants: 100,
    benefits: ['Salud', 'Trabajo remoto', 'Capacitación', 'Horario flexible'],
    required_test_id: 'big_five',
  },
  {
    title: 'Desarrollador Backend Junior (Node.js)',
    description: 'Únete a nuestro equipo backend para construir APIs REST y microservicios con Node.js y Express. Se requiere conocimiento básico de bases de datos SQL y NoSQL. Tendrás mentoría directa de ingenieros senior y participarás en code reviews diarios.',
    work_modality: 'Hybrid',
    country: 'Colombia',
    min_salary: 2800000,
    max_salary: 4200000,
    years_experience_required: 1,
    max_applicants: 80,
    benefits: ['Salud', 'Almuerzo', 'Capacitación', 'Home office 3 días'],
    required_test_id: 'big_five',
  },
  {
    title: 'Desarrollador Fullstack Junior (React + Firebase)',
    description: 'Posición ideal para desarrolladores con conocimiento en React y Firebase/Firestore. Trabajarás en aplicaciones web completas, desde la interfaz hasta la integración con servicios cloud. Se valora experiencia con Tailwind CSS y Git.',
    work_modality: 'Remote',
    country: 'Colombia',
    min_salary: 3000000,
    max_salary: 4500000,
    years_experience_required: 1,
    max_applicants: 100,
    benefits: ['Salud', 'Trabajo remoto', 'Bono anual', 'Capacitación'],
    required_test_id: 'emotional_intelligence',
  },
  {
    title: 'Desarrollador Mobile Junior (React Native)',
    description: 'Buscamos desarrollador mobile junior para crear aplicaciones iOS y Android con React Native. Conocimientos básicos en JavaScript/TypeScript y ganas de aprender son esenciales. Trabajarás con un equipo ágil usando Scrum.',
    work_modality: 'Remote',
    country: 'Colombia',
    min_salary: 2800000,
    max_salary: 4000000,
    years_experience_required: 0,
    max_applicants: 120,
    benefits: ['Salud', 'Trabajo remoto', 'Equipo proporcionado', 'Cursos online'],
    required_test_id: 'big_five',
  },
  {
    title: 'QA Engineer Junior',
    description: 'Rol de aseguramiento de calidad para alguien que quiera iniciar su carrera en testing. Realizarás pruebas manuales y automatizadas usando Cypress y Jest. Colaborarás con desarrolladores para identificar bugs y mejorar la calidad del producto.',
    work_modality: 'Hybrid',
    country: 'Colombia',
    min_salary: 2200000,
    max_salary: 3500000,
    years_experience_required: 0,
    max_applicants: 80,
    benefits: ['Salud', 'Capacitación', 'Horario flexible'],
    required_test_id: null,
  },
  {
    title: 'Desarrollador Python Junior (Data)',
    description: 'Posición junior enfocada en desarrollo con Python para pipelines de datos. Usarás pandas, SQL y herramientas de Google Cloud. No se requiere experiencia previa, pero sí conocimiento sólido de Python y SQL básico.',
    work_modality: 'Remote',
    country: 'Colombia',
    min_salary: 2800000,
    max_salary: 4200000,
    years_experience_required: 0,
    max_applicants: 100,
    benefits: ['Salud', 'Trabajo remoto', 'Certificaciones GCP', 'Bono trimestral'],
    required_test_id: 'big_five',
  },
  {
    title: 'DevOps Junior',
    description: 'Aprende DevOps en un entorno real. Trabajarás con Docker, CI/CD pipelines (GitHub Actions), y Google Cloud Platform. Buscamos a alguien con conocimiento básico de Linux y scripting (Bash o Python).',
    work_modality: 'Hybrid',
    country: 'Colombia',
    min_salary: 3000000,
    max_salary: 4500000,
    years_experience_required: 1,
    max_applicants: 60,
    benefits: ['Salud', 'Certificaciones cloud', 'Capacitación', 'Home office 2 días'],
    required_test_id: null,
  },
  {
    title: 'Desarrollador Java Junior',
    description: 'Únete al equipo de servicios empresariales. Desarrollarás microservicios con Spring Boot y Java 17+. Se requiere conocimiento básico de Java, POO y SQL. Mentoría incluida con un senior dedicado.',
    work_modality: 'On-site',
    country: 'Colombia',
    min_salary: 2500000,
    max_salary: 3800000,
    years_experience_required: 1,
    max_applicants: 80,
    benefits: ['Salud', 'Almuerzo', 'Transporte', 'Capacitación'],
    required_test_id: 'emotional_intelligence',
  },
  {
    title: 'Desarrollador Frontend Junior (Angular)',
    description: 'Buscamos talento junior con conocimientos en Angular y TypeScript para nuestro equipo de herramientas internas. Trabajarás con Angular 17+, RxJS y Material Design. Ideal para quien quiere especializarse en frontend enterprise.',
    work_modality: 'Remote',
    country: 'Colombia',
    min_salary: 2600000,
    max_salary: 4000000,
    years_experience_required: 1,
    max_applicants: 90,
    benefits: ['Salud', 'Trabajo remoto', 'Horario flexible', 'Capacitación'],
    required_test_id: 'big_five',
  },
  {
    title: 'Desarrollador UI/UX Junior',
    description: 'Posición híbrida entre diseño y desarrollo. Implementarás diseños en código usando React y Tailwind CSS. Se valora conocimiento de Figma, accesibilidad web (WCAG) y principios de diseño. No se requiere experiencia laboral previa.',
    work_modality: 'Remote',
    country: 'Colombia',
    min_salary: 2400000,
    max_salary: 3800000,
    years_experience_required: 0,
    max_applicants: 100,
    benefits: ['Salud', 'Trabajo remoto', 'Licencia Figma', 'Cursos de diseño'],
    required_test_id: 'emotional_intelligence',
  },

  // ─── Senior (5+ años) ────────────────────────────────────────────────────
  {
    title: 'Senior Frontend Engineer (React)',
    description: 'Liderarás el desarrollo frontend de productos de alto tráfico con React, TypeScript y Next.js. Se espera experiencia en arquitectura de componentes, performance optimization, testing (Jest, Cypress) y mentoría de juniors. Mínimo 5 años de experiencia en frontend.',
    work_modality: 'Remote',
    country: 'Colombia',
    min_salary: 12000000,
    max_salary: 18000000,
    years_experience_required: 5,
    max_applicants: 50,
    benefits: ['Salud premium', 'Trabajo remoto', 'Stock options', 'Bono anual', 'Presupuesto educación'],
    required_test_id: 'emotional_intelligence',
  },
  {
    title: 'Senior Backend Engineer (Go/Python)',
    description: 'Diseñarás y construirás sistemas distribuidos de alta disponibilidad usando Go y Python. Experiencia requerida en Kubernetes, gRPC, bases de datos a escala (Spanner, BigQuery) y observabilidad. Liderarás decisiones técnicas y revisarás diseños del equipo.',
    work_modality: 'Remote',
    country: 'Colombia',
    min_salary: 14000000,
    max_salary: 22000000,
    years_experience_required: 6,
    max_applicants: 40,
    benefits: ['Salud premium', 'Trabajo remoto', 'Stock options', 'Bono anual', 'Conferencias internacionales'],
    required_test_id: 'emotional_intelligence',
  },
  {
    title: 'Senior Fullstack Developer',
    description: 'Buscamos un fullstack senior para liderar el desarrollo end-to-end de aplicaciones web. Stack principal: React/Next.js + Node.js/Python + PostgreSQL/Firestore. Se requiere experiencia en CI/CD, cloud (GCP), y capacidad de tomar decisiones arquitectónicas.',
    work_modality: 'Hybrid',
    country: 'Colombia',
    min_salary: 13000000,
    max_salary: 20000000,
    years_experience_required: 5,
    max_applicants: 50,
    benefits: ['Salud premium', 'Home office 3 días', 'Stock options', 'Bono semestral', 'Capacitación'],
    required_test_id: 'big_five',
  },
  {
    title: 'Senior Site Reliability Engineer (SRE)',
    description: 'Serás responsable de la confiabilidad y disponibilidad de servicios críticos. Experiencia en Kubernetes, Terraform, monitoreo (Prometheus, Grafana), incident response y SLO/SLI. Participarás en on-call rotation y liderarás postmortems.',
    work_modality: 'Remote',
    country: 'Colombia',
    min_salary: 15000000,
    max_salary: 23000000,
    years_experience_required: 6,
    max_applicants: 30,
    benefits: ['Salud premium', 'Trabajo remoto', 'Stock options', 'Bono on-call', 'Presupuesto home office'],
    required_test_id: 'big_five',
  },
  {
    title: 'Senior Mobile Engineer (Android/Kotlin)',
    description: 'Liderarás el desarrollo de apps Android nativas con Kotlin, Jetpack Compose y arquitectura MVVM/MVI. Experiencia requerida en testing, CI/CD mobile, y publicación en Play Store a escala. Mentorarás a 2-3 desarrolladores junior.',
    work_modality: 'Remote',
    country: 'Colombia',
    min_salary: 13000000,
    max_salary: 19000000,
    years_experience_required: 5,
    max_applicants: 40,
    benefits: ['Salud premium', 'Trabajo remoto', 'Stock options', 'Equipo de última generación', 'Conferencias'],
    required_test_id: 'emotional_intelligence',
  },
  {
    title: 'Senior Data Engineer',
    description: 'Diseñarás pipelines de datos a gran escala usando Apache Beam, BigQuery y Dataflow. Se requiere experiencia en modelado de datos, SQL avanzado, Python y orquestación (Airflow/Composer). Liderarás proyectos de migración y optimización de datos.',
    work_modality: 'Remote',
    country: 'Colombia',
    min_salary: 14000000,
    max_salary: 21000000,
    years_experience_required: 5,
    max_applicants: 40,
    benefits: ['Salud premium', 'Trabajo remoto', 'Stock options', 'Certificaciones GCP', 'Bono anual'],
    required_test_id: null,
  },
  {
    title: 'Senior Security Engineer',
    description: 'Protegerás la infraestructura y las aplicaciones de Google en LATAM. Experiencia requerida en pentesting, OWASP, seguridad en cloud (GCP), IAM y compliance. Realizarás auditorías de seguridad y definirás políticas para el equipo de desarrollo.',
    work_modality: 'Hybrid',
    country: 'Colombia',
    min_salary: 16000000,
    max_salary: 24000000,
    years_experience_required: 7,
    max_applicants: 25,
    benefits: ['Salud premium', 'Home office 4 días', 'Stock options', 'Certificaciones seguridad', 'Bono anual'],
    required_test_id: 'big_five',
  },
  {
    title: 'Tech Lead — Microservicios',
    description: 'Liderarás técnicamente un equipo de 6-8 ingenieros desarrollando microservicios en Go y Java. Responsabilidades incluyen diseño de sistemas, code reviews, definición de estándares y coordinación con product managers. Se requiere experiencia liderando equipos.',
    work_modality: 'Hybrid',
    country: 'Colombia',
    min_salary: 18000000,
    max_salary: 28000000,
    years_experience_required: 8,
    max_applicants: 20,
    benefits: ['Salud premium', 'Stock options', 'Bono anual', 'Conferencias', 'Presupuesto equipo'],
    required_test_id: 'emotional_intelligence',
  },
  {
    title: 'Senior Machine Learning Engineer',
    description: 'Desarrollarás modelos de ML para productos de Google utilizando TensorFlow, Python y Vertex AI. Se requiere experiencia en MLOps, feature engineering, A/B testing y deployment de modelos a producción. Publicaciones académicas son un plus.',
    work_modality: 'Remote',
    country: 'Colombia',
    min_salary: 18000000,
    max_salary: 30000000,
    years_experience_required: 5,
    max_applicants: 30,
    benefits: ['Salud premium', 'Trabajo remoto', 'Stock options', 'GPU dedicada', 'Conferencias internacionales'],
    required_test_id: null,
  },
  {
    title: 'Senior Platform Engineer',
    description: 'Construirás la plataforma interna de desarrollo que usan cientos de ingenieros. Stack: Kubernetes, Terraform, Go, GitHub Actions. Se requiere experiencia en developer experience (DX), internal tooling y sistemas distribuidos. Impacto directo en la productividad del equipo.',
    work_modality: 'Remote',
    country: 'Colombia',
    min_salary: 15000000,
    max_salary: 22000000,
    years_experience_required: 6,
    max_applicants: 35,
    benefits: ['Salud premium', 'Trabajo remoto', 'Stock options', 'Bono anual', 'Presupuesto educación'],
    required_test_id: 'big_five',
  },
]

export async function seedJobs() {
  console.log(`Seeding ${jobs.length} job offers for company ${COMPANY_ID}…\n`)

  for (let i = 0; i < jobs.length; i++) {
    const job = jobs[i]
    const ref = await addDoc(collection(db, 'job_offers'), {
      ...job,
      company_id: COMPANY_ID,
      status: 'Active',
      created_at: serverTimestamp(),
      application_deadline: null,
    })
    console.log(`  [${i + 1}/${jobs.length}] ✓ ${job.title}  →  ${ref.id}`)
  }

  console.log('\nDone! All jobs seeded.')
}
